//------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior
//     and will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyConfiguration("CI")]
[assembly: AssemblyCompany("TEKsystems")]
[assembly: AssemblyProduct("Seat Plan")]
[assembly: AssemblyCopyright("Copyright (C)2017 TEKsystems All rights reserved.")]
[assembly: AssemblyTrademark("TEK Seat Plan")]
[assembly: ComVisible(false)]
[assembly: CLSCompliant(true)]
[assembly: Guid("29e3b677-3663-4db5-9c45-8c0c7ccf1b22")]